### ISSUE TITLE
Waiting for SSH to be available...

### ISSUE THREAD

**Issue by fractal1977** [rancher-plugins/rancher-machine-driver-oci#10]
I followed the minimalistic documentation here.
The OCI connection is ok but the VM/nodes are stucks with " Waiting for SSH to be available..." and the cluster respawn new nodes to configure...again and again with the same SSH message.

is there thing/step to configure, i missed ?

Thx

**Comment by fractal1977** [comment]
Ok OCI VCN problem...
Have you a way to properly configure the VCN and security lists for the deployed nodes to access internet ? or others ressources/ports needed for nodes/worker  deployment ?

**Comment by jlamillan** [comment]
Nodes attach to an existing and pre-configured VCN. So, you'll need to adjust your VCN's security list before creating the cluster. I'd recommend starting with something like the following:
 
**Ingress:**
* 22 (SSH) from the Rancher source IP to the node(s) being created (try starting with a CIDR of 0.0.0.0/0)
* 2376 (Docker) from the Rancher source IP to the node(s) being created (again, try starting with a CIDR of 0.0.0.0/0)
*  2376, 2379, 2380, 6443, and 10250 between all the node(s) (nodes will use private IP addresses for internal communication regardless if they use public IPs)

**Egress:**
* Access to the Internet 0.0.0.0/0 to download scripts, pull images from the Docker repository, and otherwise access Internet
